var dotenv = require('dotenv');
dotenv.load();

var fs = require('fs');
var cloudinary = require('cloudinary').v2;


var uploads = {};

// set your env variable CLOUDINARY_URL or set the following configuration ==> I'm currently using the .env  option
/*cloudinary.config({
  cloud_name: '',
  api_key: '',
  api_secret: ''
});*/

console.log( "** ** ** ** ** ** ** ** ** Uploads ** ** ** ** ** ** ** ** ** **");


const myTag = 'node.js upload'

// File upload (example for promise api)
cloudinary.uploader.upload('darage.jpg',{tags:myTag, height: 500, width: 500, crop: "limit"})
.then(function(image){
  console.log();
  console.log("** File Upload (Promise)");
  console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
  console.log("* "+image.public_id);
  console.log("* "+image.url);
  console.log("* "+image.height);
  console.log("* "+image.width);
})
.catch(function(err){
  console.log();
  console.log("** File Upload (Promise)");
  if (err){ console.warn(err);}
});


//  console.log();
 console.log( "> That's it. You can now open the URLs above in a browser");
 console.log( "> and check out the generated images.")

